project/diary/urls.py
from django.urls import path
from .import views

app_name = "diary"

urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add, name="add"),
    path("update/<int:pk>/",views.update,name='update'),
    path("delete/<int:pk>/",views.delete,name='delete'),
    path("detail/<int:pk>/",views.detail,name='detail'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include("diary.urls")),
]

project/diary/models.py
from django.db import models
from django.utils import timezone



class Day(models.Model):
    title = models.CharField("たいとる",max_length=200)
    text = models.TextField("本文")
    date = models.DateTimeField("日付",default=timezone.now)

project/diary/forms.py
from django import forms
from .models import Day


class DayCreateForm(forms.ModelForm):

    class Meta:
        model =Day
        fields ="__all__"

project/diary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import DayCreateForm
from .models import Day



def index(request):
    context = {
        "day_list":Day.objects.all(),
    }
    return render(request,"diary/day_list.html",context)
    paginate_by = 3


def add(request):
    form = DayCreateForm(request.POST or None)
    if request.method =="POST" and form.is_valid():
        form.save()
        return redirect("diary:index")    
    context = {
        "form":form
    }
    return render(request,"diary/day_form.html",context)

def update(request,pk):
    day = get_object_or_404(Day,pk=pk)

    form = DayCreateForm(request.POST or None, instance=day)

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('diary:index')

    context = {
        'form':form
    }
    return render(request,'diary/day_form.html',context)
#ここからでりーと

def delete(request,pk):
    day = get_object_or_404(Day,pk=pk)

    if request.method == 'POST':
        day.delete()
        return redirect('diary:index')

    context = {
        'day':day
    }
    return render(request,'diary/day_confirm_delete.html',context)


#ここからでぃてーる
def detail(request,pk):
    day = get_object_or_404(Day,pk=pk)


    context = {
        'day':day
    }
    return render(request,'diary/day_detail.html',context)

project/diary/templates/diary/base.html
<!doctype html> 

<html lang="ja"> 

  <head> 
    <title>わああああああああああ</title> 
    <!-- Required meta tags --> 

    <meta charset="utf-8"> 

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 

  

    <!-- Bootstrap CSS --> 

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
  </head> 
  <body>
    <div class="container">
    <nav class="nav">
        <a class="nav-link" href="{% url "diary:index" %}">一覧</a>
        <a class="nav-link" href="{% url "diary:add" %}">追加</a>
    </nav>
    {% block content %}
    {% endblock %}
    </div>

  

    <!-- Optional JavaScript --> 

    <!-- jQuery first, then Popper.js, then Bootstrap JS --> 

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> 

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script> 

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> 

  </body> 

</html> 

project/diary/templates/diary/day_confirm_delete.html
{% extends "diary/base.html" %}

{% block content %}
<form action=""method="POST">
    <table class="table">
        <tr>
            <th>タイトル</th>
            <td>{{ day.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ day.text }}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ day.date }}</td>
        </tr>
    </table>
    <p>こちらのデータを削除します。</p>
    <button type="submit" class="btn btn-primary">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

project/diary/templates/diary/day_detail.html
{% extends "diary/base.html" %}

{% block content %}
    <table class="table">
        <tr>
            <th>タイトル</th>
            <td>{{ day.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ day.text | linebreaksbr }}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ day.date }}</td>
        </tr>
    </table>

{% endblock %}

project/diary/templates/diary/day_form.html
{% extends "diary/base.html" %}

{% block content %}
<form action=""method="POST">
    <table class="table">
        <tr>
            <th>タイトル</th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ form.text }}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ form.date }}</td>
        </tr>
    </table>
    <button type="submit" class="btn btn-primary">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

project/diary/templates/diary/day_list.html
{% extends "diary/base.html" %}

{% block content %}
<h1>日記一覧</h1>
<table class="table">
    <thread>
        <tr>
            <th>タイトル</th>
            <th>日付</th>
            <th>#</th>
            <th>#</th>
        </tr>
    </thread>
    <tbody>
        {% for day in day_list %}
        <tr>
            <td><a href="{% url 'diary:detail' day.pk %}">{{ day.title }}</td>
            <td>{{ day.date }}</td>
            <td><a href='{% url "diary:update" day.pk %}'>更新</a></td>
            <td><a href='{% url "diary:delete" day.pk %}'>削除</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}